"""empty message

Revision ID: 126cd1405b3c
Revises: df8376ab2977
Create Date: 2018-12-08 17:30:54.596412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '126cd1405b3c'
down_revision = 'df8376ab2977'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('test', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
